extmap = list(
  arff = c("foreign::read.arff"),
  clipboard = c("clipr::read_clip_tbl"),
  #csv = c("::"), # import_delim
  #csv2 = c("::"), # import_delim
  csvy = c("csvy::read_csvy"),
  #dat = c("::"), # import_delim
  dbf = c("foreign::read.dbf"),
  dif = c("utils::read.DIF"),
  dta = c("haven::read_dta","foreign::read.dta"),
  eviews = c("hexView::readEViews"),
  feather = c("feather::read_feather"),
  fortran = c("utils::read.fortran"),
  fst = c("fst::read.fst"),
  #fwf = c("::"), readr::fwf_widths
  #html = c("::"), lots of stuff to sort out
  json = c("jsonlite::fromJSON"),
  matlab = c("rmatio::read.mat"),
  mtp = c("foreign::read.mtp"),
  ods = c("readODS::read_ods"),
  #psv = c("::"), import_delim
  r = c("base::dget"),
  rda = c("base::load"),
  rdata = c("base::load"),
  rds = c("base::readRDS"),
  rec = c("foreign::read.epiinfo"),
  sas7bdat = c("haven::read_sas"),
  sav = c("haven::read_sav","foreign::read.spss"),
  spss = c("haven::read_por"),
  syd = c("foreign::read.systat"),
  #tsv = c("::"), import_delim
  #txt = c("::"), import_delim, try this one first
  xls = c("readxl::read_xls"),
  xlsx = c("readxl::read_xlsx","openxlsx::read.xlsx"),
  #xml = c("::"), complex
  xpt = c("haven::read_xpt","foreign::read.xport"),
  yml = c("yaml::read_yaml")
)